"""reconfigure the models

Revision ID: ef5c79802689
Revises: 2502578e99fb
Create Date: 2019-12-05 18:06:30.330144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5c79802689'
down_revision = '2502578e99fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualities', sa.Column('height', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualities', 'height')
    # ### end Alembic commands ###
